name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image (x86_64)
        id: build_x86
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/<hnidanka>/zadanie2:latest

      - name: Build and Push Docker image (arm64)
        id: build_arm
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64
          push: true
          tags: ghcr.io/hnidanka/zadanie2:latest-arm64
      - name: Run Snyk test
        uses: snyk/actions/docker@master
        with:
       image: ghcr.io/hnidanka/zadanie2:latest
       - name: Push Docker image to GitHub Packages
        uses: docker/build-push-action@v2
        with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/hnidanka/zadanie2:latest


